name: Deploy Code X Web to GitHub Pages

on:
  push:
    branches:
      - main # أو اسم الفرع الرئيسي عندك إذا كان master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Web Platform
        run: flutter create . --platforms web

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web